server:
   port: 9020
   
spring:
   application:
      name: contact-service
      
eureka:
   client:
      service-url:
         defaultZone: http://localhost:9030/eureka
         
   instance:
      preferIpAddress: true
      hostname: localhost
      