server:
   port: 9030

spring:
   application:
      name: eureka-server
      
         
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9030/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    
    

   