server:
   port: 9030

spring:
   application:
      name: eureka-server
      
         
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.7:9030/eureka
    fetch-registry: false
    register-with-eureka: false

    
    

   