server:
   port: 9010
   
spring:
   application:
      name: user-service
      
eureka:
   client:
      service-url:
         defaultZone: http://192.168.0.7:9030/eureka
         
   instance:
      preferIpAddress: true
      hostname: 192.168.0.7
      