server:
   port: 9040
   
      
eureka:
   client:
      service-url:
         defaultZone: http://192.168.0.7:9030/
         
   instance:
      preferIpAddress: true
      hostname: 192.168.0.7
      
spring:
  application:
     name: api-getway
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: http://192.168.0.7:9010
        predicates:
        - Path=/users/**
      - id: contact-service
        uri: http://192.168.0.7:9020
        predicates:
        - Path=/contact/**